### ISSUE TITLE
No data since 2016-01-29...

### ISSUE THREAD

**Issue by LoveMyData** [planningalerts-scrapers/cockburn#1]
From: Eric Tam
Date: 14 April 2017 at 08:11
Subject: Online Application Search
To: itsupport@cockburn.wa.gov.au

Hi IT

I am browsing your online portal and I can't seem to find any development applications. It is a little hard to believe there is zero application being submitted in the last day, this month even last month.

The link I am using is http://masterview.cockburn.wa.gov.au/MasterViewUI/modules/applicationmaster/default.aspx?page=search

Can you please have a look and see is there some issue?

Many Thanks
Eric

**Comment by henare** [comment]
Any reply so far @LoveMyData? :email:

**Comment by LoveMyData** [comment]
Nothing but found the new link... finally....
https://ecouncil.cockburn.wa.gov.au/eProperty/P1/eTrack/eTrackApplicationSearchResults.aspx?Field=S&Period=TM&r=P1.WEBGUEST&f=%24P1.ETR.SEARCH.STM

**Comment by LoveMyData** [comment]
Period can be TW, TM, LM (thisweek, thismonth, lastmonth)
